[project]
name = "speculative-decoding"
version = "0.1.0"
description = "Example script that implements speculative decoding."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.2",
    "transformers>=4.41",
    "accelerate"
]
